title: Your awesome title
author: nemesisjoe86
email: josephwarren8613@gmail.com
description: I really don't know what to say about this but you can be very much interested in what you mean 

# social links
twitter_username: NemyJoe04
github_username:  Nemesisjoe86
Snapchat username: Josephwar86

show_excerpts: true # 2
